version: "3.8"

services:
  comfy:
    platform: linux/x86_64 #1 miniconda 설치 에러, 도커 아키텍처를 명시하여 fix
    # user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    restart: always
    volumes:
      - ./models:/app/models
      - ./output:/app/output
      - ./input/:/app/input
      - ./custom_nodes:/app/custom_nodes
    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
